# @package retargeting
type: VECTOR_WRIST_JOINT
setting_id: 3
ablation_option: 0
optimizer:
  class: VectorWristJointOptimizer
  params:
    huber_delta: 0.02
    opt_ftol_abs: 0.00001
    opt_maxtime: 0.05
targets:
  leap:
    wrist_link_name: wrist
    link_pairs:
      - [world, thumb_tip_center]
      - [wrist, thumb_tip_center]
      - [wrist, finger1_tip_center]
      - [wrist, finger2_tip_center]
      - [wrist, finger3_tip_center]
      - [thumb_tip_center, finger1_tip_center]
      - [thumb_tip_center, finger2_tip_center]
      - [thumb_tip_center, finger3_tip_center]
      - [thumb_tip_center_lower, thumb_tip_center]
      - [finger1_tip_center_lower, finger1_tip_center]
      - [finger2_tip_center_lower, finger2_tip_center]
      - [finger3_tip_center_lower, finger3_tip_center]
  shadow:
    wrist_link_name: ee_link
    link_pairs:
      - [world, thtip]
      - [ee_link, thtip]
      - [ee_link, fftip]
      - [ee_link, mftip]
      - [ee_link, rftip]
      - [ee_link, lftip]
      - [thtip, fftip]
      - [thtip, mftip]
      - [thtip, rftip]
      - [thtip, lftip]
      - [thdistal, thtip]
      - [ffdistal, fftip]
      - [mfdistal, mftip]
      - [rfdistal, rftip]
      - [lfdistal, lftip]
joint_limit_overrides:
  - indices: [9, 10, 13, 14, 17, 18]
    lower: -0.2
