defaults:
  - apps: benchmark_result
  - _self_

result: ${app.result}
output_root: ${app.output_root}
output_dir: ${app.output_dir}
plot: ${app.plot}
plot_root: ${app.plot_root}
plot_dir: ${app.plot_dir}
