defaults:
  - apps: offline_retarget_avp
  - retargeting_profiles: vector_wrist_joint_panda_leap_paxini
  - detection_sources: avp
  - teleoperation_modes: simulation
  - solvers: nlopt_slsqp
  - _self_

data: ${app.data}
start: ${app.start}
end: ${app.end}
stride: ${app.stride}
output_root: ${app.output_root}
output_dir: ${app.output_dir}
run_name: ${app.run_name}

post:
  benchmark:
    enabled: false
    output_root: ${output_root}
    output_dir: null
    plot: true
    plot_root: ${output_root}
    plot_dir: null
  visualize:
    enabled: false
    viewer:
      fps: 20.0
      port: 9217
      no_robot_mesh: false
      trail_length: 120
