defaults:
  - apps: replay_avp
  - retargeting_profiles: vector_wrist_joint_panda_leap_paxini
  - detection_sources: avp
  - teleoperation_modes: simulation
  - solvers: nlopt_slsqp
  - _self_

data: ${app.data}
result: ${app.result}
start: ${app.start}
end: ${app.end}
stride: ${app.stride}
viewer:
  fps: ${app.viewer.fps}
  port: ${app.viewer.port}
  no_robot_mesh: ${app.viewer.no_robot_mesh}
  trail_length: ${app.viewer.trail_length}
